### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'attrib'

### ISSUE THREAD

**Issue by maabdelghaffar** [ungarj/s2reader#6]
Hello, I just tried running s2reader on .SAFE example and i got the following:
Not sure if i am doing something wrong 

./test-s2reader.py S2A_MSIL1C_20170809T100031_N0205_R122_T32TQT_20170809T100028.SAFE

Traceback (most recent call last):
  File "./test-s2reader.py", line 18, in <module>
    for granule in s2_product.granules:
  File "/usr/local/lib/python2.7/dist-packages/s2reader/s2reader.py", line 108, in granules
    for _id in product_organisation.findall("Granule_List")
  File "/usr/local/lib/python2.7/dist-packages/s2reader/s2reader.py", line 152, in __init__
    self.granule_identifier = granule.attrib["granuleIdentifier"]

**Comment by ungarj** [comment]
Hi,

which ``test-s2reader.py`` script do you mean? Also, there seems to be some lines missing from the Traceback. It would be helpful if tere was more information. I also downloaded ``S2A_MSIL1C_20170809T100031_N0205_R122_T32TQT_20170809T100028.SAFE`` via DHUS and at least ``s2_inspect`` didn't throw an exception.

However, ``s2_transform`` tries to get metadata which is not there (see #7).

Could you provide more information, please? Thanks!

**Comment by maabdelghaffar** [comment]
Hello,

Its actually the test script here:
 
import s2reader
with s2reader.open("example.SAFE") as s2_product:
    # returns product start time
    print s2_product.product_start_time
    # returns product stop time
    print s2_product.product_stop_time
    # returns product generation time
    print s2_product.generation_time
    # returns product footprint
    print s2_product.footprint
    # iterates through product granules
    for granule in s2_product.granules:
        # returns granule path
        print granule.granule_path
        # returns granule footprint
        print granule.footprint

    # returns list of image paths of a specific band (e.g. all .jp2 files for
    # band 1)
    print s2_product.granule_paths(1)

And the missing line from the error is :
AttributeError: 'NoneType' object has no attribute 'attrib'

**Comment by ungarj** [comment]
sorry, I'm not able to reproduce:

```python
#!/usr/bin/env python

import s2reader

with s2reader.open("S2A_MSIL1C_20170809T100031_N0205_R122_T32TQT_20170809T100028.SAFE") as s2_product:
    # returns product start time
    print s2_product.product_start_time
    # returns product stop time
    print s2_product.product_stop_time
    # returns product generation time
    print s2_product.generation_time
    # returns product footprint
    print s2_product.footprint
    # iterates through product granules
    for granule in s2_product.granules:
        # returns granule path
        print granule.granule_path
        # returns granule footprint
        print granule.footprint

    # returns list of image paths of a specific band (e.g. all .jp2 files for
    # band 1)
    for path in s2_product.granule_paths(1):
        print path
```
outputs in
```
2017-08-09T10:00:31.026Z
2017-08-09T10:00:31.026Z
2017-08-09T10:00:28.000000Z
POLYGON ((12.76505472189437 46.80226079397767, 12.79544699326002 46.88905976721978, 12.84670982115561 47.03584954425716, 12.90190841422861 47.18152516796582, 12.95203569645472 47.3284889299196, 13.00632561220178 47.47435697186212, 13.05746877282669 47.62115126473941, 13.10932661202968 47.76787427490872, 13.1136883705921 47.77979738071082, 13.13525847527747 47.77915707233463, 13.05902986504502 46.79367068819608, 12.76505472189437 46.80226079397767))
S2A_MSIL1C_20170809T100031_N0205_R122_T32TQT_20170809T100028.SAFE/GRANULE/L1C_T32TQT_A011130_20170809T100028
POLYGON ((13.05902986511192 46.79367068772223, 13.13525847536845 47.77915707185738, 11.671539426387 47.82260755951877, 11.62219565550016 46.83565572672744, 13.05902986511192 46.79367068772223))
S2A_MSIL1C_20170809T100031_N0205_R122_T32TQT_20170809T100028.SAFE/GRANULE/L1C_T32TQT_A011130_20170809T100028/IMG_DATA/S2A_OPER_MSI_L1C_TL_SGS__20170809T153134_A011130_T32TQT_B01.jp2
```

the line numbers in your error message are odd as well. are you sure you have the latest version of the code?

**Comment by maabdelghaffar** [comment]
Right, the one i was using installed from pip, i downloaded your master branch and it worked now. 
thanks

**Comment by ungarj** [comment]
thanks for pointing it out! we should publish a new pip release.
